/**
 * Award is a record of a perk being awarded to a member. An award acts as a
 * certificate that binds a perk to a member.
 */
export interface Award {
  id: string; // UUID generated by the server on award.
  awarder: string; // The authorized ID of the user who granted the award.
  awardee: string; // The ID of the member who received the award.
  mint_id: string; // ID of minted perk awarded to grantee.
  awarded_at: string; // Timestamp the award was granted.
}

/**
 * MintedPerk is a perk that has been minted and is ready to be awarded.
 */
export interface MintedPerk {
  id: string; // Generated on the server when the perk is minted.
  type: string; // The name of the perk to be minted.
  minter: string; // The ID of the authorized user who minted the perk.
  minted_at: string; // Timestamp the perk was minted.
  max_uses: number; // The number of times this perk can be consumed.
  milliseconds: number; // The number of milliseconds this perk is valid for.
  available: number; // Number of uses remaining.
  activated?: string; // Timestamp the award was activated.
}

/**
 * Perk to be minted.
 */
export interface Perk {
  name: string; // The unique name of the perk.
  description: string; // Description of the perk.
  default_max_uses: number; // The default number of times this perk can be consumed.
  default_milliseconds: number; // The default number of milliseconds this perk is valid for.
}
